### ISSUE TITLE
preopens question

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/preview2-prototyping#141]
hi,

i'm trying to use the `host` command to run adapted preview1 modules.  i was able to run simple "hello" style modules.
eg.
```
wasm-tools component new hello.wasm --adapt wasi_snapshot_preview1.wasm -o chello.wasm
host chello.wasm
```

however, for a bit more complex modules which involve filesystem operations, i failed to find a way to specify preopens.
(i'm looking for functionality equiv of `wasmtime run --dir`)

i guess this `get-directories` thing is related. https://github.com/bytecodealliance/preview2-prototyping/blob/d3bd2bc36a9caed047002e62561fc439c391df47/wit/preopens.wit#L16

any help? thank you.

**Comment by pchickey** [comment]
I am actually implementing those command line flags right now, sit tight

**Comment by yamt** [comment]
ok. thank you for the info.

**Comment by yamt** [comment]
https://github.com/bytecodealliance/preview2-prototyping/pull/142 seems working for me. thank you.
```
spacetanuki% ./target/release/host --mapdir aaa::${HOME}/git/toywasm/wat/wasi ~/git/wasm/wasm-tools/ctoywasm.wasm -- --wasi aaa/hello.wasm
2023-04-17 06:27:46 (1681712866.343301000): set_nonblocking failed with 28
2023-04-17 06:27:46 (1681712866.343353000): set_nonblocking failed with 28
2023-04-17 06:27:46 (1681712866.343362000): set_nonblocking failed with 28
hello
Error: error while executing at wasm backtrace:
    0: 0x6a29a - wit-component:adapter:wasi_snapshot_preview1!wasi_snapshot_preview1::bindings::exit::exit::h581bbd3be0a9ad99
    1: 0x69582 - wit-component:adapter:wasi_snapshot_preview1!proc_exit
    2: 0x6e095 - wit-component:shim!adapt-wasi_snapshot_preview1-proc_exit
    3: 0x842d - <unknown>!__wasi_proc_exit
    4: 0x800b - <unknown>!_Exit
    5: 0x9a13 - <unknown>!exit
    6: 0x205c - <unknown>!main
    7: 0x8084 - <unknown>!__main_void
    8: 0x1cbf - <unknown>!_start
    9: 0x6b601 - wit-component:adapter:wasi_snapshot_preview1!main

Caused by:
    Exited with i32 exit status 0
spacetanuki% 
```

**Comment by pchickey** [comment]
I should also make it so that an exit 0 doesnt show the backtrace!

**Comment by yamt** [comment]
> I should also make it so that an exit 0 doesnt show the backtrace!

probably it shouldn't show the backtrace for `proc_exit` at all.

**Comment by pchickey** [comment]
correct. coffee hasnt kicked in yet
