### ISSUE TITLE
How to handle environment variables in Preview 2 and its implementations

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/preview2-prototyping#31]
Per recent discussion on Zulip and elsewhere, we've been trying to reconcile the desired environment variable interface for Preview 2 with existing interfaces in Preview 1, POSIX, etc.  The goal for the former is that the component explicitly imports functions (or values, once they're implemented) for each environment variable it needs, expressed as a star import in WIT.  However, Preview 1 and POSIX provide a dynamic, implicit interface for getting environment variables, and it's not clear how to bridge the Preview 1 and Preview 2 interfaces in the adapter.  And, more generally, how to support existing software and libraries which expect a POSIX-like interface.

One option would be to abandon the idea of a "one-size-fits-all" adapter and instead generate a unique adapter on-the-fly for a given component whenever the set of environment variables needed becomes available -- e.g. either build time, deploy time, or even just prior to instantiation.  A variation on this would be to start with a core "one-size-fits-all" adapter that uses a dynamic interface for accessing env vars, which is in turn virtualized by a dynamically-generated mini-adapter when the set of env vars needed becomes available.

The other option is to simply use a dynamic interface for Preview 2 (e.g. #28) and aim for a fully explicit, typed interface for both CLI arguments and env vars in later releases of `wasi-environment`, etc. (which could even be released concurrently with Preview 2).  In other words, Preview 2 would be the last POSIX-like WASI release (and the last "monolithic" WASI release altogether) with subsequent `wasi-environment` implementations providing virtualizations on top of Preview 2, each releasing on its own schedule.  If you squint, this is effectively the same solution as the second variation of the option above -- we'd release a star-imports-based `wasi-environment` concurrently with WASI Preview 2 (which will have its own, dynamic `wasi-environment`).  The star imports version can be implemented as an on-the-fly-generated virtualization on top the dynamic interface.  Likewise for implicit, stringly-typed vs. explicit, properly-typed CLI arguments (`wasi-arguments`?).

@tschneidereit @lann and @fibonacci1729 and I discussed this earlier today, and the conclusion was at generating a unique adapter for all of WASI on-the-fly would be overkill, so we're leaning towards something like the second option listed above.  Specifically, we're thinking the `command` function should take a parameter representing the list of environment variables, similar to how it already takes a parameter representing the CLI arguments.  For reactors, it would be a similar story, except that it would be a parameter to the reactor initialization function we've been discussing.  In either case, an additional, virtualizing adapter could be used to wrap the dynamic, implicit interface in a static, explicit, typed one.  And of course, toolchains that provide built-in support for the static, explicit interface (e.g. pragmas to declare the set of env vars needed) will not need any adapter at all.

@sunfishcode @pchickey @alexcrichton thoughts or concerns?

**Comment by alexcrichton** [comment]
Personally I'm in camp "let's leave env vars as a POSIX-y interface" so that all sounds good to me. I'm not against star imports and such per-se but I feel there are far too many unknowns about that solution to weigh it against an implementation as you've proposed here.

**Comment by dicej** [comment]
As @lann pointed out, the reactor case could be handled via a host-provided import (e.g. `environ`) for getting vars if we want to keep the init function unparameterized, and that might save a little time since the host could implement it lazily or not even export it if the component doesn't import it.  And as @tschneidereit mentioned, it could also be a global variable.

**Comment by sunfishcode** [comment]
I agree that the dynamic interface sounds like the right thing to do at this time.

**Comment by dicej** [comment]
Ok, so I think we have consensus that there should be a dynamic interface for env vars in Preview 2.

@sunfishcode and I had a conversation this morning about both env vars and preopens -- particularly with regard to reactors vs commands.  We concluded that, on the command side, we'd like to add two new parameters to the `command` function: a `list<tuple<string, string>>` for env vars and a `list<tuple<descriptor, string>>` (i.e. file descriptor and path) for preopened directories.  On the reactor side, we'd like to add a new world for what Dan is calling "CLI reactors" which has an exported function called `initialize` which also takes the same env var and preopen parameters (but not the other `command` parameters, i.e. no stdin, stdout, and CLI args).  LIke `command`, we'd implement `initialize` in the preview1->preview2 adapter, and the host would be required to call it prior to calling any other exports.

The reasoning for this approach (versus e.g. zero-argument imports or global variables) is that it is more explicit and less ambient.  As Dan put it: "I don't think we really want environment variable APIs to be super easy to mix in with other worlds. We really would like to push people to writing wit interfaces for things, rather than just sticking a 'use environment from whatever' in their world files."

Thoughts about this approach?

Meanwhile, I'm going to close #28 and rework it according to the above.

**Comment by sunfishcode** [comment]
This approach sounds reasonable to me.

**Comment by sunfishcode** [comment]
Implemented in #28.
