### ISSUE TITLE
Wasmtime no longer have wasmtime::component::Error

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/preview2-prototyping#32]
This [PR](https://github.com/bytecodealliance/wasmtime/pull/5397) removes the `wasmtime::component::Error<E>`, which is used to define `HostResult` in "host/src/lib.rs". I was trying to update the code to use 

```rust
type HostResult<T, E> = anyhow::Result<Result<T, E>>;
```

to satisfy the generated `Result` type from wasmtime component. Am I on the right direction? If yes, then I can try to create a pull request to update to the newest wasmtime on the main branch.

**Comment by pchickey** [comment]
The whole HostResult thing was a dumb design, I never should have shipped it. My apologies.

Presently, yes, you can use an alias with that nested result to keep code compiling.

The idea is that we can now use the `trapping_error_type` argument to the macro (see https://github.com/bytecodealliance/wasmtime/pull/5397) to replace those cases with a more ergonomic design. This time is opt in to prevent breaking things if we come up with a better design in the future.

I have been out with back problems that prevent me from typing much, so I haven't updated this repo to use the new design. Dan  started a PR with https://github.com/bytecodealliance/preview2-prototyping/pull/26 but I think it would be welcome if you wanted to finish up that PR.

**Comment by Mossaka** [comment]
Thanks for your response, and please take care of yourself! Ah yes, I think #26 is exactly what I was implementing!
