### ISSUE TITLE
Unreachable on proc_exit

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/preview2-prototyping#56]
I'm getting the following for a failed main command:

```
RuntimeError: unreachable
    at proc_exit (wasm://wasm/9a2d00b2:wasm-function[47]:0x1c01)
    at wasm://wasm/866f5096:wasm-function[31]:0x309
    at __wasi_proc_exit (wasm://wasm/24985656:wasm-function[12479]:0x525663)
    at _start (wasm://wasm/24985656:wasm-function[20]:0x531d)
    at command (wasm://wasm/9a2d00b2:wasm-function[26]:0x737)
    at command (file:///Users/gbedford/Projects/js-component-runtime-proto/dist/component-runtime.js:139:24)
    at file:///Users/gbedford/Projects/js-component-runtime-proto/test.js:3:13
```

The `exit` import function is being correctly called with a failure result.

Two possible bugs here:
* The `exit` import function is not called on successful completion, only failure - I would have thought this would either fire for both or not?
* Immediately after calling the `exit` import function the above unreachable instruction is hit. I'm not exactly sure what it is due to, but would have expected the command function itself to propagate the error result.

**Comment by guybedford** [comment]
I can also replicate this with a main returning `-1` in the host executor giving:

```
Error: error while executing at wasm backtrace:
    0: 0x1f17 - <unknown>!wasi_snapshot_preview1::bindings::wasi_exit::exit::h26eb39d88b2939a5
    1: 0x1c0a - <unknown>!proc_exit
    2: 0x9257701 - <unknown>!<wasm function 31>
    3: 0x51ef32 - <unknown>!__wasi_proc_exit
    4: 0x8eed - <unknown>!_start
    5:  0x742 - <unknown>!command

Caused by:
    Exited with i32 exit status 1
```

This may or may not be specific to the exact binary I'm using, let me know if a replication would help further here.

**Comment by sunfishcode** [comment]
Does your wasi-exit exit implementation actually exit? :-) If it does [this](https://github.com/guybedford/wasi-command-export-printf/blob/main/wasi/exit.js#L2) and returns, then it's continuing back into the polyfill, which does an `unreachable` because it's not expecting `exit` to return.

**Comment by guybedford** [comment]
No it does not, in which case this error now makes sense I agree!

It might be useful to have the error properly provide a WASI error though in this case with a WASI error code, eg exitDidNotExit or something like that.

This also explains why it only happens in the failure case though, thanks.

**Comment by sunfishcode** [comment]
If the host exit function doesn't exit, we don't have anywhere to report an error code to. I have now submitted #62 which makes it print a message before aborting, which hopefully helps.

**Comment by sunfishcode** [comment]
We now print a more informative message when aborting in this case. As mentioned above, there's nowhere else we can report the error to. Please file a new issue if there are any further problems here!
