### ISSUE TITLE
which version of `wasm-tool` is expected?

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/preview2-prototyping#63]
i tried to follow the instructions is `README.md`. but i couldn't.

with wasm-tool commit `main` as of writing this (e077155c17107320cd8616a62fa6254a60d509b2)
```
spacetanuki% ./target/debug/wasm-tools component new foo.wasm --adapt /tmp/p/wasi_snapshot_preview1.wasm -o c.wasm
Error: decoding custom section component-type:wasi

Caused by:
    unsupported component version: 0xa (at offset 0x0)
spacetanuki% ./target/debug/wasm-tools component new foo.wasm --adapt /tmp/p/wasi_snapshot_preview1.command.wasm -o c.wasm
Error: decoding custom section component-type:wasi

Caused by:
    unsupported component version: 0xa (at offset 0x0)
spacetanuki% 
```

with wasm-tool commit immediately before the component version bump (b6233ed48f1d5b7c4adfa5656e426d739a08c0fa)
```
spacetanuki% ./target/debug/wasm-tools component new foo.wasm --adapt /tmp/p/wasi_snapshot_preview1.command.wasm -o c.wasm
Error: failed to encode a component from module 

Caused by:
    module requires an import interface named `wasi_snapshot_preview1`
spacetanuki% ./target/debug/wasm-tools component new foo.wasm --adapt /tmp/p/wasi_snapshot_preview1.wasm -o c.wasm
thread 'main' panicked at 'cannot import anonymous type across interfaces', crates/wit-component/src/encoding.rs:438:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
spacetanuki% 
```

**Comment by alexcrichton** [comment]
The component version bump hasn't made its way into downstream tooling yet, it's waiting on https://github.com/bytecodealliance/wasm-tools/pull/867 to kick off that process (hopefully resolved by the end of this week).

Otherwise the second panic you're running into looks like a bug with the `wasm-tools` repository, as that should work with this repository.

**Comment by alexcrichton** [comment]
I believe the various issues have been addressed with the latest versions of tools, so I'm going to close.

**Comment by yamt** [comment]
> I believe the various issues have been addressed with the latest versions of tools, so I'm going to close.

yes. when i tried a few days ago, it worked.
