### ISSUE TITLE
Clocks time show a random value ?

### ISSUE THREAD

**Issue by fuxiaohei** [bytecodealliance/preview2-prototyping#92]
I read test https://github.com/bytecodealliance/preview2-prototyping/blob/main/test-programs/src/bin/time.rs

```rust
assert_eq!(
    SystemTime::UNIX_EPOCH + Duration::from_secs(1431648000),
    SystemTime::now()
);
```

it means `now()` is a fixed value? `wasi-clocks` is a mock implementation for now ?

I write an example:
https://github.com/fuxiaohei/wasmtime-component-wasi-preview-test/blob/main/wasm_lib/src/lib.rs

and show result: https://github.com/fuxiaohei/wasmtime-component-wasi-preview-test/actions/runs/4219533802/jobs/7324978752#step:5:601

```
Run component: target/wasm32-wasi/release/wasm_lib.component.wasm
Hello, world!, 2050-02-10 1:09:05.0 +00:00:00
```

**Comment by pchickey** [comment]
Yep that looks like a bug. I'll investigate but it may take me a few days to get to it.

**Comment by fuxiaohei** [comment]
I write a common module example:

https://github.com/fuxiaohei/wasmtime-component-wasi-preview-test/blob/main/wasm_module/src/main.rs

```rust
fn print() {
    let utc = time::OffsetDateTime::now_utc();
    println!("Hello, world!, {:?}", utc);
}

fn main() {
    print();
}
```
then run it in actions:

```bash
cargo build --release --target wasm32-wasi -p wasm_module
wasmtime target/wasm32-wasi/release/wasm_module.wasm
```
https://github.com/fuxiaohei/wasmtime-component-wasi-preview-test/actions/runs/4238574036/jobs/7365790008#step:5:677

```
Hello, world!, 2023-02-22 1:53:37.021344677 +00:00:00
```

https://github.com/fuxiaohei/wasmtime-component-wasi-preview-test/actions/runs/4238574036/jobs/7365790008#step:5:648

but component module shows:

```
Hello, world!, 2046-05-02 21:02:31.0 +00:00:00
```

**Comment by alexcrichton** [comment]
Thanks for confirming! I think I've fixed this in https://github.com/bytecodealliance/preview2-prototyping/pull/93
